# Generated by Django 5.2.8 on 2025-11-30 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('servermanager', '0002_alter_emailsendlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('comment', 'Comment'), ('article', 'Article')], max_length=10, verbose_name='review type')),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='review time')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('need_modification', 'Need Modification')], max_length=20, verbose_name='review result')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='review comment')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'review history',
                'verbose_name_plural': 'review histories',
                'ordering': ['-review_time'],
            },
        ),
    ]
