# Generated by Django 5.2.8 on 2025-12-10 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_remove_comment_created_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modify', 'Need Modification')], default='pending', max_length=20, verbose_name='audit status'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('comment', 'Comment'), ('article', 'Article')], default='comment', help_text='Comment or Article', max_length=20, verbose_name='Audit Type')),
                ('content_id', models.IntegerField(verbose_name='Content ID')),
                ('original_content', models.TextField(blank=True, verbose_name='Original Content')),
                ('audit_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modify', 'Need Modification')], default='pending', max_length=20, verbose_name='audit status')),
                ('audit_opinion', models.TextField(blank=True, null=True, verbose_name='audit opinion')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='audit time')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='auditor')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-audit_time'],
            },
        ),
    ]
