# Generated by Django 5.2.8 on 2025-12-10 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_remove_comment_created_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAuditProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Comment Audit Dashboard',
                'verbose_name_plural': 'Comment Audit Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('comments.comment',),
        ),
        migrations.AddField(
            model_name='comment',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_modification', 'Need Modification')], default='pending', help_text='Comment audit status', max_length=20, verbose_name='audit status'),
        ),
        migrations.CreateModel(
            name='CommentAuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='audit time')),
                ('old_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_modification', 'Need Modification')], max_length=20, verbose_name='old status')),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_modification', 'Need Modification')], max_length=20, verbose_name='new status')),
                ('audit_opinion', models.TextField(blank=True, help_text='Auditor comments and opinions', max_length=500, null=True, verbose_name='audit opinion')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='auditor')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_histories', to='comments.comment', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'comment audit history',
                'verbose_name_plural': 'comment audit histories',
                'ordering': ['-audit_time'],
            },
        ),
    ]
