# Generated by Django 5.2.8 on 2025-12-10 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bloguser_options_remove_bloguser_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('comment_reply', '评论回复'), ('system_notice', '系统通知'), ('article_approved', '文章审核通过'), ('article_rejected', '文章审核拒绝')], default='system_notice', max_length=20, verbose_name='通知类型')),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送用户')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_time'],
            },
        ),
    ]
