# Generated by Django 5.2.8 on 2025-12-24 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bloguser_options_remove_bloguser_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('type', models.CharField(choices=[('comment_reply', 'Comment Reply'), ('system_notice', 'System Notice'), ('article_approve', 'Article Approve'), ('article_reject', 'Article Reject')], default='system_notice', max_length=20, verbose_name='type')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='related object id')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='related object type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notification',
                'ordering': ['-creation_time'],
            },
        ),
    ]
