# Generated by Django 5.2.8 on 2025-11-29 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='site name')),
                ('site_description', models.CharField(max_length=200, verbose_name='site description')),
                ('site_keywords', models.CharField(max_length=200, verbose_name='site keywords')),
                ('site_url', models.URLField(default='https://example.com', verbose_name='site url')),
                ('site_logo', models.ImageField(blank=True, upload_to='blog/logos/', verbose_name='site logo')),
                ('site_favicon', models.ImageField(blank=True, upload_to='blog/favicons/', verbose_name='site favicon')),
                ('site_analytics', models.TextField(blank=True, help_text='Enter your analytics code here.', verbose_name='site analytics')),
                ('site_copyright', models.TextField(blank=True, verbose_name='site copyright')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'blog setting',
                'verbose_name_plural': 'blog settings',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url', models.URLField(default='https://example.com', verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('index', models.IntegerField(default=0, help_text='Enter a positive integer to set the order of the link. The smaller the number, the higher the priority.', verbose_name='index')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ['index', 'created_time'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url', models.URLField(default='https://example.com', verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('index', models.IntegerField(default=0, help_text='Enter a positive integer to set the order of the link. The smaller the number, the higher the priority.', verbose_name='index')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ['index', 'created_time'],
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True, help_text='If type is HTML or Text, enter the content here.', verbose_name='content')),
                ('type', models.CharField(choices=[('h', 'HTML'), ('t', 'Text'), ('r', 'Recent Articles'), ('a', 'Archive'), ('c', 'Categories'), ('t', 'Tags')], default='t', max_length=1, verbose_name='type')),
                ('sequence', models.IntegerField(default=0, help_text='Enter a positive integer to set the order of the sidebar. The smaller the number, the higher the priority.', verbose_name='sequence')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'sidebar',
                'verbose_name_plural': 'sidebars',
                'ordering': ['sequence', 'created_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('excerpt', models.TextField(blank=True, verbose_name='excerpt')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='p', max_length=1, verbose_name='status')),
                ('comment_status', models.CharField(choices=[('o', 'Open'), ('c', 'Closed')], default='o', max_length=1, verbose_name='comment status')),
                ('type', models.CharField(choices=[('a', 'Article'), ('p', 'Page')], default='a', max_length=1, verbose_name='type')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
                ('article_order', models.IntegerField(default=0, help_text='Enter a positive integer to set the order of the article. The smaller the number, the higher the priority.', verbose_name='article order')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-created_time'],
                'get_latest_by': 'created_time',
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='version number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blog.article', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'article version',
                'verbose_name_plural': 'article versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('index', models.IntegerField(default=0, help_text='Enter a positive integer to set the order of the category. The smaller the number, the higher the priority.', verbose_name='index')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['index', 'created_time'],
                'unique_together': {('name', 'parent_category')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='blog.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('body', models.TextField(verbose_name='body')),
                ('status', models.CharField(choices=[('n', 'New'), ('a', 'Approved'), ('r', 'Rejected')], default='n', max_length=1, verbose_name='status')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified time')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='article')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.comment', verbose_name='parent comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='blog.tag', verbose_name='tags'),
        ),
    ]
