# Generated by Django 5.2.8 on 2025-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modify', 'Need Modification')], default='pending', max_length=20, verbose_name='audit status'),
        ),
    ]
