# Generated by Django 5.2.8 on 2025-11-30 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogsettings_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approval_comment',
            field=models.TextField(blank=True, null=True, verbose_name='approval comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_modification', 'Need Modification')], default='pending', max_length=20, verbose_name='approval status'),
        ),
        migrations.AddField(
            model_name='article',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='article',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('r', 'Review Pending')], default='p', max_length=1, verbose_name='status'),
        ),
    ]
