# Generated by Django 5.2.8 on 2025-12-10 12:31

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20251210_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleversion',
            options={'ordering': ['-version_number'], 'verbose_name': '文章版本', 'verbose_name_plural': '文章版本'},
        ),





        migrations.AlterField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blog.article', verbose_name='关联的文章ID'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='文章正文（版本快照）'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='文章标题（版本快照）'),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='版本号，从1开始递增'),
        ),

    ]
