# Generated by Django 5.2.8 on 2025-11-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creation_time'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='notification',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra Data'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read Time'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_content_type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Related Content Type ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Related Object ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.IntegerField(default=0, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_reply', 'Comment Reply'), ('system', 'System Notification'), ('audit', 'Article Approval')], max_length=20, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
    ]
